// Ideia é fazer algo que a pessoa tenha que decodificar um trecho;
// Por exemplo, uma frase, onde cada letra representa um numero... 
// Usando uma tabela externa para checar as letras, e transformar em numero.
